AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  KwetterEventBus: 
    Type: AWS::Events::EventBus
    Properties: 
      Name: "KwetterEventBus"

  KwetterEventBusDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "KwetterEventBusDLQ"

  KwetterEventBusDLQPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref KwetterEventBusDLQ
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: "sqs:SendMessage"
            Resource: !GetAtt KwetterEventBusDLQ.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !GetAtt KwetterEventBus.Arn

  KwetterEventBusmessageContentCheckingFunctionDLQRule:
    Type: AWS::Events::Rule
    Properties:
      Name: "KwetterEventBusmessageContentCheckingFunctionDLQRule"
      EventBusName: !Ref KwetterEventBus
      EventPattern:
        source:
          - "com.example.kwetter"
      Targets:
        - Id: "KwetterEventBusDLQTarget"
          Arn: !GetAtt KwetterEventBusDLQ.Arn
          RetryPolicy:
            MaximumRetryAttempts: 1
            MaximumEventAgeInSeconds: 60
          DeadLetterConfig:
            Arn: !GetAtt KwetterEventBusDLQ.Arn

  messageContentCheckingFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: messages/lambda/messageContentChecking/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures: [arm64]
      Role: !GetAtt messageContentCheckingFunctionRole.Arn

  messageContentCheckingFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaLoggingPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
        - PolicyName: EventBridgePutEventsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: events:PutEvents
                Resource: !GetAtt KwetterEventBus.Arn
        - PolicyName: DynamoDBReadPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: dynamodb:GetItem
                Resource: !GetAtt KwetterMessagesDynamoDBTable.Arn # Replace with your DynamoDB table resource ARN
        - PolicyName: DynamoDBWritePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: dynamodb:PutItem
                Resource: !GetAtt KwetterMessagesDynamoDBTable.Arn # Replace with your DynamoDB table resource ARN

  MessageCRUDFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: messages/lambda/messageCRUD/ # folder where your main program resides
      Handler: bootstrap
      Runtime: provided.al2
      Architectures: [arm64]
      Role: !GetAtt MessageCRUDFunctionRole.Arn

  MessageCRUDFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaLoggingPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*
        - PolicyName: DynamoDBReadPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: dynamodb:GetItem
                Resource: !GetAtt KwetterMessagesDynamoDBTable.Arn # Replace with your DynamoDB table resource ARN
        - PolicyName: DynamoDBWritePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: dynamodb:PutItem
                Resource: !GetAtt KwetterMessagesDynamoDBTable.Arn # Replace with your DynamoDB table resource ARN

  KwetterMessagesDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "KwetterMessagesDynamoDBTable"
      AttributeDefinitions:
        - AttributeName: "GUID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "GUID"
          KeyType: "HASH"
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  KwetterAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "KwetterAPIGateway"
        paths:
            /postMessage:
              post:
                consumes:
                  - application/json
                produces:
                  - application/json
                parameters: []
                responses: {}
                x-amazon-apigateway-integration:
                  type: aws
                  httpMethod: POST
                  uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${messageContentCheckingFunction.Arn}/invocations"

  KwetterUserPool:
    Type: AWS::Cognito::UserPool 
    Properties:
      UserPoolName: "KwetterUserPool"
      DeletionProtection: ACTIVE 
      Policies:
        PasswordPolicy:
          RequireLowercase: true
          RequireSymbols: false
          RequireNumbers: true
          MinimumLength: "8"
          RequireUppercase: true
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: false
      AutoVerifiedAttributes:
        - email

  KwetterUserpoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref KwetterUserPool
      Domain: "kwetter"

  KwetterUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref KwetterUserPool
      ClientName: "KwetterUserPoolClient"
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: True
      AllowedOAuthFlows: 
        - code
      CallbackURLs: 
        - "http://localhost:5173/auth/callback"
      LogoutURLs:
        - "http://localhost:5173/"
      SupportedIdentityProviders:
        - COGNITO 
      AllowedOAuthScopes:
        - phone
        - email
        - openid

  KwetterAPIGatewayPermissionTestFunction:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt messageContentCheckingFunction.Arn
      Principal: apigateway.amazonaws.com

  APIGatewayEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !Ref KwetterEventBus
      EventPattern:
        source:
          - "api.gateway"
        detail-type:
          - "API Gateway Request"
      Targets:
        - Arn: !GetAtt messageContentCheckingFunction.Arn
          Id: "InvokeTestFunction"
 
  EventRulePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt MessageCRUDFunction.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt messageContentCheckingFunctionEventRule.Arn

  messageContentCheckingFunctionEventRule:
    Type: AWS::Events::Rule
    Properties:
      EventBusName: !Ref KwetterEventBus # Replace with your event bus name
      EventPattern:
        detail-type:
          - "MessageCreation" # Replace with your detail type
      Targets:
        - Arn: !GetAtt MessageCRUDFunction.Arn
          Id: "MessageCRUDFunction"
          RetryPolicy:
            MaximumRetryAttempts: 1
            MaximumEventAgeInSeconds: 60
          DeadLetterConfig:
            Arn: !GetAtt KwetterEventBusDLQ.Arn
